### ISSUE TITLE
License Inconsistentcy

### ISSUE THREAD

**Issue by Simoyd** [LuizZak/FastBitmap#11]
The root folder has a license file showing the MIT license, but FastBitmap.cs has "The MIT License (MIT)" as a title with the "GNU General Public License" content underneath...

It's unclear which license applies to FastBitmap.cs. I'm guessing this was just an oversight and FastBitmap.cs just needs to be updated to the MIT license?

**Comment by LuizZak** [comment]
Yes, it's MIT-licensed, I must have missed the source files. I'll update them to be consistent. Thanks for pointing that out!
