### ISSUE TITLE
doesn't recognise image over 600 pixel height

### ISSUE THREAD

**Issue by whatohyou** [LuizZak/FastBitmap#13]
From 600 pixel height, it will show everything color black.

**Comment by LuizZak** [comment]
Do you have any test case that reproduces for this bug so I can take a look? I just tried real quick to handle 600x600 and 601x601 images and it seemed ok at first.

**Comment by whatohyou** [comment]
Sorry it seems there was an error in my code.

**Comment by LuizZak** [comment]
Alrighty, No worries!
