### ISSUE TITLE
[Nuget package] unnecessary dependency - OpenCover

### ISSUE THREAD

**Issue by UlyssesWu** [LuizZak/FastBitmap#2]
When I install the nuget package, I find it requires for OpenCover - which is actually not needed.

**Comment by LuizZak** [comment]
Hmm yes, added that for the unit tests project, but seems like the main target doesn't need it really. I'll look into how to make sure it's not referenced on the main package unnecessarily.

**Comment by LuizZak** [comment]
I've pushed 1.1.2 that should fix the issue, can you please verify?

**Comment by UlyssesWu** [comment]
Yes, no more dependency needed. Good job👍
